| 操作     | URL                  | パスヘルパー           | HTTPメソッド | 役割の概要                                      | link_toメソッドでの呼び出し方                               | 省略形                                     |
|----------|----------------------|------------------------|--------------|-----------------------------------------------|--------------------------------------------------|--------------------------------------------|
| Index    | /items               | `items_path`           | GET          | すべてのアイテムを表示する                        | `<%= link_to 'All Items', items_path %>`          | 省略不可                                     |
| Show     | /items/:id           | `item_path(@item)`     | GET          | 特定のアイテムを表示する                          | `<%= link_to 'Show Item', item_path(@item) %>`    | `<%= link_to 'Show Item', @item %>`          |
| New      | /items/new           | `new_item_path`        | GET          | 新しいアイテムを作成するためのフォームを表示する          | `<%= link_to 'New Item', new_item_path %>`        | 省略不可                                     |
| Edit     | /items/:id/edit      | `edit_item_path(@item)`| GET          | 特定のアイテムを編集するためのフォームを表示する          | `<%= link_to 'Edit Item', edit_item_path(@item) %>`| 省略不可                                     |
| Update   | /items/:id           | `item_path(@item)`     | PATCH/PUT    | 特定のアイテムを更新する                          | 省略不可                                         | 省略不可                                     |
| Create   | /items               | `items_path`           | POST         | 新しいアイテムをデータベースに保存する                | 省略不可                                         | 省略不可                                     |
| Destroy  | /items/:id           | `item_path(@item)`     | DELETE       | 特定のアイテムを削除する                          | `<%= link_to 'Delete Item', item_path(@item), method: :delete, data: { confirm: 'Are you sure?' } %>` | `<%= link_to 'Delete Item', @item, method: :delete, data: { confirm: 'Are you sure?' } %>` |
